version: '3.1'

services:
  eureka:
    build: eureka-server
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
    - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}

  gateway:
    build: gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    ports:
      - "8443:8443"

  config-server:
    build: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
      - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
    volumes:
      - $PWD/config-repo:/config-repo



#  gateway-server:
#    image: ${container.name}:${container.tag}
#    ports:
#      - "8989:8989"
#    depends_on:
#      - config-server
#      - eureka
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8989/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
