spring:
  config:
    import: "optional:configserver:http://config-service:8888"
    activate:
      on-profile: docker

  output:
      ansi:
        enabled: always
server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


---
spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8888"
