eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8060
spring:
  application:
    name: authorisation
  datasource:
    url: jdbc:h2:mem:ticketAppTest
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false

logging:
  level:
    org.springframework.security: DEBUG

application:
  config:
    authorisation-url: http://localhost:8070