server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: C:\Developers\IdeaProjects\ticket-platform\config-repo
  docker:
    compose:
      enabled: false

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        native:
          searchLocations: file:/config-repo
