# read configuration from config server
server:
   port: 8061



eureka:
   instance:
      hostname: localhost
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
   output:
      ansi:
         enabled: always



   config:
      import: "optional:configserver:http://config-service:8888"
      activate:
         on-profile: docker
---
spring:
   application:
      name: discovery
   config:
      import: "optional:configserver:http://localhost:8888"